### ISSUE TITLE
Some format/encoder combos output files with double file extensions

### ISSUE THREAD

**Issue by klaurence** [Myzel394/Alibi#10]
Examples that I've found are `THREE_GPP` format/`Auto` encoder outputting `.3gp.aac` files and `MPEG_2_TS` format/Auto encoder outputting `.ts.aac` files. I presume that this is unintentional and that they should be only `.3gp` and `.ts` files.

There might be more combinations when not using the `Auto` encoder option.

**Comment by Myzel394** [comment]
Should be fixed with the new version
