### ISSUE TITLE
[Bug] Unable to activate Flashlight with Quicksettings while recording Video

### ISSUE THREAD

**Issue by materialred** [Myzel394/Alibi#102]
If you are recording Video, you can't activate the flashlight via the quicksettings, only through Alibi. 

Version: 0.5.0 (13)
Device: Google Pixel 8 Pro
Rom: crDroid 10.3 (Android 14)

**Comment by Myzel394** [comment]
This is expected. On Android, if there's an app using the camera, other apps (including the quicksettings) can't access any camera modules (including the flashlight).

**Comment by materialred** [comment]
Would it possible if Alibi has a Quicksettings Tile for flashlight, so that it can be used?
