### ISSUE TITLE
[Feature Request] Customizable file name?

### ISSUE THREAD

**Issue by dzx-dzx** [Myzel394/Alibi#105]
Right now the name of the files are the date at which the recording begins, but it could be not helpful when the recording begins days ago, running in background. 

I'd like an option to chagne the name to the date of the end of recording, or more perfectly, the date of the actual beginning of the recording. ("The end" minus time of recording)

**Comment by dzx-dzx** [comment]
I've noticed that this feature https://github.com/Myzel394/Alibi/issues/83 would overwrite the last saved audio file. Is this a bug related to this issue?

**Comment by Myzel394** [comment]
@dzx-dzx Thanks for noticing that. I've opened a PR, which should fix this

**Comment by dzx-dzx** [comment]
Thanks!
