### ISSUE TITLE
Info about output file metadata

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#11]
Is the output file (.ogg or what you want) fully cleared by metadata, phone model, microphone type, etc that can identify the record maker?

I didn't use Alibi yet and I am not a developer.

**Comment by Myzel394** [comment]
Alibi itself only adds the current settings as metadata (batch duration, max duration) + the date the recording was started. This doesn't work yet, but I'll fix this bug. I don't think Android itself adds any other metadata and after a quick metadata check on a recording, I couldn't find any other metadata.
