### ISSUE TITLE
[Feature request] Ability to record internal audio for calls

### ISSUE THREAD

**Issue by vvsagar** [Myzel394/Alibi#113]
I love the app and I was wondering if it is possible to include an option to also record the internal audio which will help to record calls. Would that be feasible?

**Comment by Myzel394** [comment]
Hey,

this has been asked in #92, unfortunately Android does not seem to allow apps to record calls. The dev team is also not very transparent about this, at least I couldn't find much about that.

There are apparently some tricks by making Alibi an admin app, rooting your phone or installing Alibi as a system app. However, I will **not support** any of those methods, sorry.
