### ISSUE TITLE
Option for Video only - no audio.

### ISSUE THREAD

**Issue by rudolfmu** [Myzel394/Alibi#119]
Thank you for giving us your wonderful app!

In Germany there are (old) strict laws against recording the spoken word (audio) but much less strict laws for taking pictures (including video).
So a video only recording is much more useful as evidence. Removing audio is no option (as it is tampering).
So I would kindly ask to add a video only (no audio) option for us Germans. Maybe in other countries this may be the same, I don't know.

**Comment by Myzel394** [comment]
You can already do this.
Hold down on the video recorder, and unselect "Record with Audio".


Btw, I'm not a lawyer but https://www.gesetze-im-internet.de/stgb/__201a.html may apply in this case.
Please keep in mind that it's your responsibility to use Alibi in accordance with the law. Alibi is not meant to be used for secretly recording videos without the consent of other parties.

**Comment by rudolfmu** [comment]
Thank you!
