### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Allium0** [Myzel394/Alibi#12]
I have translated Alibi into Chinese, and here is the relevant file.
[Alibi.zip](https://github.com/Myzel394/Alibi/files/12311051/Alibi.zip)

**Comment by Myzel394** [comment]
Thank you very much for your help!
Just to make sure I'm not using the wrong locale, is this `zh` or `zh-CHT` (aka simplified or traditional Chinese)?

**Comment by Allium0** [comment]
> Thank you very much for your help!
> Just to make sure I'm not using the wrong locale, is this `zh` or `zh-CHT` (aka simplified or traditional Chinese)?

You're welcome. Please use zh-CN.

**Comment by Myzel394** [comment]
Added, will be published with the next release. I actually didn't know Android has pre defined locales, nice to see that! :D
