### ISSUE TITLE
Crash when saving video

### ISSUE THREAD

**Issue by hjek** [Myzel394/Alibi#124]
I've used Alibi to record a video. When I click **Save Recording from Sunday, 8 September 2024**, Alibi crashes. A 0 byte video file is
created.

I wonder if there are alternative ways of extracting the video from the app storage. I can see that Alibi uses 3,4GB of space, which I assume includes the recording. I have around 40GB of free disk space so the issue is not low storage.

**Comment by Myzel394** [comment]
There was an issue with the filename, can you try installing the v0.5.3 update from GitHub and try again?

Alternatively, you can wait until the update is approved on Google Play, or you can try setting the Batches Folder to media or a custom one

**Comment by sourcevault** [comment]
Alibi version: v0.5.3
Downloaded from: F-Droid
phone: Xioami Redmi 4A
Android Version: 8.1
Batch size: 3 minute audio

I am having similar issue with saving audio on SD card ( which is set as folder to save ). It saves, but only shows the last batched file ( only 3 minute ). I can still use the files stored in `.recording` but would be nice to see it as one file when needed.
