### ISSUE TITLE
Crowdin

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Myzel394/Alibi#16]
Can we all use [https://crowdin.com/](https://crowdin.com/) to translate Alibi ? Would be easier.

**Comment by Myzel394** [comment]
Good call! I think there is a competitor for open source software for free available, I'll compare them and check which one fits better. @mondlicht-und-sterne do you maybe know what competitors there are available?

**Comment by mondlicht-und-sterne** [comment]
Transifex (I no longer translate there)
And Weblate still exists.

**Comment by Myzel394** [comment]
I think I'd prefer to go with Weblate as you can host it yourself. I'll try setting it up and then looking if it's good for my projects.

**Comment by mondlicht-und-sterne** [comment]
> I think I'd prefer to go with Weblate as you can host it yourself. I'll try setting it up and then looking if it's good for my projects.

@Myzel394  If I know where you are going to translate, which instance, I can translate there.

**Comment by Myzel394** [comment]
I decided I'll go with Crowdin, as it's very easy to use and has generous plans for FLOSS software. I'm currently trying to set it up (https://github.com/Myzel394/Alibi/pull/30), but I'll ping you once it's ready! :D

**Comment by Myzel394** [comment]
@mondlicht-und-sterne Everything set up, Alibi can now be translated using Crowdin: https://crowdin.com/project/alibi - Thanks for opening the issue! :)
