### ISSUE TITLE
What is batch?

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#2]
Is it a minimum time interval between two records?

I would like to have the last four hours of recording available to me at all times, divided into 15 minutes of recording for each session.

How do I set up the app?

**Comment by Myzel394** [comment]
Alibi works a bit different than that, it saves the last 30 minutes (or any other duration you specify) whenever you save the recording. Batch duration is more of an advanced topic,. Basically Alibi does the following when you start a recording: 

Let's assume you have a batch duration of 1 minute and a maximum duration of 30 minutes. Alibi will start recording for one minute, save that recording, and start a new 1-minute recording. This will continue until you stop or save the recording. As soon as 30 minutes have been recorded, it will start deleting the oldest recording (to save up storage).

> I would like to have the last four hours of recording available to me at all times, divided into 15 minutes of recording for each session.

You can set the max duration to 4 hours and the batch duration to 15 minutes for that. When you save your recording, all recordings will be concatenated to one single file.
