### ISSUE TITLE
Always On Functionality

### ISSUE THREAD

**Issue by domportera** [Myzel394/Alibi#20]
i see a lot of potential for this to essentially be a pocket security camera or personal evidence collector, and as such id like to have it running at low quality at all times in the background automatically, caching the last X amount of time with the option for export. this is basically how it works now, which is wonderful, just missing the auto-start. thanks for making this app !

**Comment by Myzel394** [comment]
That's great to hear!

Regarding your auto-start question, is your question related to #8?

**Comment by domportera** [comment]
it sounds like it could be, though I haven't exactly been as thoughtful or considerate of my flash storage as that poster 😅 im just thinking a "record on system start" option, though a scheduler sounds like a more sustainable solution

**Comment by domportera** [comment]
Ive been thinking about this a bit. to save storage hardware and potentially make development a bit easier, it might be a nice feature to have a constant in-RAM buffer that the user can specify the size of. then when the save button is pressed it is stored to disk as an audio file. i.e if someone has RAM to spare, they can set aside like 100mb - X GB as a recording buffer

**Comment by Myzel394** [comment]
Hey @domportera, quick update to stay you informed:

>  just missing the auto-start

This will be added with #39

> if someone has RAM to spare, they can set aside like 100mb - X GB as a recording buffer

Unfortunately, it doesn't look like this is possible. I need to specify a file the recorder can write to. We could write to the caches folder, which might be in RAM, which might don't, if there's low memory for example. But then the batches could be deleted anytime if the system needs more storage.

I will close this issue in favor of #39
