### ISSUE TITLE
Up to 48 hours "max duration"

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#25]
I want to choose the batches very calmly. I save by default up to two days of recordings and I only decide later what I keep and what I reject.

![1000094341](https://github.com/Myzel394/Alibi/assets/113377431/5661d445-2860-464e-8ac6-3f2f48a2744d)

**Comment by Myzel394** [comment]
Increased the limit, you'll be able to set a max duration of 99 hours and 99 minutes, which is a little bit over 4 days. If you ever need more, feel free to open an issue :D

**Comment by Myzel394** [comment]
> I just wrong the calculation. For some reasons I typed 480 hours 🤔

I'm sorry but I don't understand what you mean.

> The hours field missing in my phone. Bug or I wrong something?

I haven't published a release yet :D Will take so probably in the next few days
