### ISSUE TITLE
Hide notification button in notifications' bar

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#26]
In case of emergency one can quickly hide the notification, even if it has previously enabled. It is a security feature.

![1000094343](https://github.com/Myzel394/Alibi/assets/113377431/1a087e30-d3c2-40b3-9f01-9275d5bbc76d)

**Comment by Myzel394** [comment]
You can disable the notification in your Android settings, I think you'll need to long hold on it and then you can disable it. The app should still run in the background.

**Comment by Myzel394** [comment]
I see. Unfortunately I can't hide the notification from within the app as Android expects a notification to be shown for the app to be able to run in the background. Your only option therefore is to disable it previously; especially if you are afraid someone might take a closer look at you, I'd take a few precautions.
