### ISSUE TITLE
Unlabeled drawer in notifications' bar

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#28]
Not full explanation, just "save" and "pausing" buttons in notifications' bar, without explicit explanations that lead to record an audio track. No hints, just neutral buttons and drawer.

**Comment by Myzel394** [comment]
Yeah so we could add like fake notification labels; I'd propose the following labels:

* Timer - Just shows the time and allows pausing and saving
* Music Player - Shows "Playing song: BabyShark" and also allows pausing and saving
* Fake weather - Simply shows fake weather

What do you think @serrq ? Do you have any other ideas?

**Comment by Myzel394** [comment]
I can add a changing track name at the beginning of the notification, but I won't make a changing song name notification title. 

> Do you add also the song cover art? 🤭

We can show a music player icon instead of the Alibi icon.

**Comment by Myzel394** [comment]
@serrq if you'd like to try it out already, [you can find a debug build here](https://github.com/Myzel394/Alibi/actions/runs/6626641336?pr=33). Download the "artifact" file at the bottom, extract it and install `app-universal-debug.apk`

**Comment by Myzel394** [comment]
> I wait the fdroid version. I don't install apk from other sources. Sorry.

No problem but keep in mind that since I'm using IzzyOnDroid, the APK is directly fetched from GitHub :D
