### ISSUE TITLE
Consequences of continuous recording on flash nand health

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#3]
Will continuous recording lead to a shorter longevity of the storage memory?

Might you force your app to always record on different, random sectors? That would help it not write the same tracks over and avoiding to burn them out (hardware side).

**Comment by Myzel394** [comment]
To be honest, I don't know much enough about hardware to answer this question. I guess it will not really dramatically reduce the health, as it's "only" audio. As far as I know, Android already produces a lot of files when writing logs for example; I expect the hardware to be quite robust nowadays.

You can compare using Alibi to using any other ordinary Audio Recorder app in the background.

> Might you force your app to always record on different, random sectors? That would help it not write the same tracks over and avoiding to burn them out (hardware side).

I have no control over that, I just tell Android to write a file to the cache, the rest is handled internally.

**Comment by Myzel394** [comment]
> Mine it has been just a consideration, not an indictment of your work.

No worries! It's good when people think outside the box! :D

**Comment by Heath123** [comment]
> Might you force your app to always record on different, random sectors? That would help it not write the same tracks over and avoiding to burn them out (hardware side).

I’m pretty sure the flash chip does that automatically (it’s called wear levelling)
