### ISSUE TITLE
Autostart triggers

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#31]
It would be useful having an autostart for certain conditions:

• wifi: lose or gain a wifi local network
• mic: when environment sound overcomes X db then start recording for Y time
• gps: when I leave or gain a certain geographical aerea

And so on. Have you other triggers idea?

**Comment by Myzel394** [comment]
I will not add this but you can achieve this with something like Tasker once #15 is closed

**Comment by Myzel394** [comment]
There may be FLOSS apps like Tasker. I can't tell as I don't use such apps :/
