### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#34]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, ETH, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, FTM, XMR addresses available for donations (addresses have to be copyable).

![1000092943](https://github.com/Myzel394/Alibi/assets/113377431/c8ec68da-19fb-49d9-acb5-3efa6d69b733)

**Comment by Myzel394** [comment]
> TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, FTM, XMR

Uhhh so I already have added Bitcoin and Monero on the README - I don't know what the other currencies are.

**Comment by Myzel394** [comment]
I have added support for more crypto in the README.md. I'm not sure whether I'll add it into the app, I'm first gonna have to think about it.
