### ISSUE TITLE
add note to promt the user to check if the useage of the app is compatible with local law

### ISSUE THREAD

**Issue by SnoutBug** [Myzel394/Alibi#4]
My proposal is to add a small note to the start up screen, something along the lines of: "some bodies might regulate how or when you are allowed to record a conversation, please check in with your local law", since the app implies that it should be used without anyones knowledge, to provide an "alibi".

In some countries (eg. germany) it is illegal to record a conversation without consent, therefore a note like the one above would be nice to have.

I noticed you put up a message to "use the software at the users own risk" but I think this is not a really conclusive statement, since this could also apply to data security and the hardware lifespan.

**Comment by Myzel394** [comment]
How you use Alibi is entirely up to you. You can use it like a dashcam, you can use it as a proof of innocence, you can use it to stalk other people - any technology that can be used for good can also be used for bad. With this app, I didn't invent secret recording, that is already possible for years and there are apps out there that are much better specialized for that than Alibi. You as the user are responsible on how you use the technology provided to you. To make this clear, I added a note at the beginning.
Maybe I should rephrase it a bit to make it clearer, thanks for your opinion here @SnoutBug.
