### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#44]
Might you removing the "recording" written?

Ehm, now I have only BNB (Smart Chain), FTM and XEC. Might you add these coins in next update?

PS: the donation section is too much hidden in my opinion. Might you making it more visible?

![1000094430](https://github.com/Myzel394/Alibi/assets/113377431/0f044289-8f64-4bd2-98bb-74730c5f73e7)

![1000094432](https://github.com/Myzel394/Alibi/assets/113377431/83c1a5e9-31e4-4042-b5e0-cea6f758d4c2)

**Comment by Myzel394** [comment]
> Might you removing the "recording" written?

Makes sense, gonna remove that.

> Ehm, now I have only BNB (Smart Chain)

If I understood correctly, BNB is based on Ethereum and hence uses the same addresses. At least on my side I can use my Ethereum address to receive BNB.

> and XEC

do you mean iExec (RLC)? It also seems to be using Ethereum. ^^

> FTM

Also using Ethereum address :D Btw, you might want to check out my repo https://github.com/Myzel394/contact-me. I list general details (such as donations info) there and digitally sign it. This way you can be 100% sure it's really me.

> PS: the donation section is too much hidden in my opinion. Might you making it more visible?

I think it's okay there. I don't want to place it too obvious as I personally find it intrusive. If people want to support my development, I'm pretty sure they will quickly go to the about section anyway :D

**Comment by Myzel394** [comment]
btw, thanks for trying out Alibi so fast after the new version has been released ^^

**Comment by Myzel394** [comment]
> XEC is eCash.
> 
> https://e.cash/

I see, unfortunately my multi-coin wallet doesn't support eCash :/ and I already have too many wallets now, so eCash won't be supported (until my wallet supports it); sorry :/

**Comment by Myzel394** [comment]
> Let's practice.

nice! :D

![image](https://github.com/Myzel394/Alibi/assets/50424412/00a4af24-8573-426f-a1b6-6e86aca3440c)

received it, thank you! :)

**Comment by Myzel394** [comment]
> FTM and BNB

BNB? You just sent some BNBs :D and FTM also uses the Ethereum address. I'm not going to write down all Ethereum based cryptos since they all use the same Ethereum address - which is listed on my page :D

**Comment by Myzel394** [comment]
> What is the public key? The longer one? Or the shortest one?

There is only one. The box shows the fingerprint and a button to copy the actual key.

**Comment by Myzel394** [comment]
> Sorry I am not practice with this encryption standard (my Tutanota privider not even has it).

It's a default public key in text format :D afaik tutanota doesn't support gpg encryption at all and instead use their own encryption software :/

> Fingerprint is a pubkey?

Inside the box, under text and above the button you can see the fingerprint of the key.

> In the box there is the private key?

If you click on "Copy GPG Key" you copy the **public key**. You **do not** post the private key as otherwise all integrity / authenticity is lost.

> Am I wrong something?

You just need to copy the key and save it somewhere. If you want to verify my signature you'll need to use some GPG software.
