### ISSUE TITLE
feature req: option to not merge recording

### ISSUE THREAD

**Issue by nutpantz** [Myzel394/Alibi#45]
I would like an option to not merge recordings.  I do need to monitor and record a long time frame but i only need sections of it not the whole 3 hours. 
Not merging the entire recording but keeping the batches in sections (preferably with a little overlapping) would be the best option for me.

**Comment by Myzel394** [comment]
We could add an advanced option to let the user decide where they want to store the batches. One could then store them in the Documents folder for example.

**Comment by Myzel394** [comment]
> A dedicated one? Alibi folder?

You can set it up however you like. Currently, Alibi saves the batches in the internal encrypted folder for security reasons.

**Comment by Myzel394** [comment]
@nutpantz you can try out a debug version at https://github.com/Myzel394/Alibi/pull/50 if you'd like to - I'll keep this PR open a bit to catch any issues and will then publish a new update with it.
