### ISSUE TITLE
app not responding

### ISSUE THREAD

**Issue by lettersforword365** [Myzel394/Alibi#47]
Hi,

I often get app not responding errors when I return to Alibi after leaving it running for a while. Usually, the app screen goes black then I see the popup and no audio appears to be recorded. If I reopen the app, it starts recording all over again.

Could you please look into this, or advise me on solutions/workarounds?

**Comment by Myzel394** [comment]
> I often get app not responding errors

Does Alibi crash or do the other apps crash?

Could you try recording the screen?

**Comment by Myzel394** [comment]
Also, what OS are you using? Which Android version are you running on?

**Comment by Myzel394** [comment]
@lettersforword365 please update Alibi to the latest version. Hopefully the update fixes your issue. If it still persists, feel free to reopen the issue
