### ISSUE TITLE
Fastlane: de-DE shortdesc too long

### ISSUE THREAD

**Issue by IzzySoft** [Myzel394/Alibi#49]
Currently, `short_description.txt` for `de-de` has 98 chars. The specs only allow for 80 chars, so all beyond that is being cut off. Could you please fix that (and maybe limit the field length with Crowdin)? Thanks!

**Comment by Myzel394** [comment]
Thanks for the hint! Is the 80 char limit a hard requirement? If not, I'd be okay with the text being a bit too long

**Comment by IzzySoft** [comment]
> Is the 80 char limit a hard requirement?

As I wrote:

> all beyond that is being cut off.

Which means, in the middle of a word if that's what is at position 80. And while you might be OK with that, it means all-times warnings in my inbox, as my "quality check job" does not feel OK with it :wink:

And if "middle of a word" doesn't worry you, you might get some shit
ake, which is not everyone's taste :see_no_evil:

(in this example, "shitake" is turned into :hankey: – as that's where char 80 could be. Flies might be happy, you probably not :wink:)

**Comment by IzzySoft** [comment]
Thanks!
