### ISSUE TITLE
File chooser doesn't appear

### ISSUE THREAD

**Issue by Notunderscore** [Myzel394/Alibi#58]
Hello, I'm having a problem where the file picker doesn't appear after finishing a recording/ clicking on "save recording".

I have looked at the android logcat and saw no errors. I also tried reinstalling & resetting the app and it still doesn't work.

Here is a screencap of what happened:

https://github.com/Myzel394/Alibi/assets/71441113/96f2ffa9-d1e8-4c3b-bbf9-6caca2e2a15e

Is this the file picker (DocumentUI) or the app at fault here? 

Regards, 
Notunderscore

**Comment by Myzel394** [comment]
This should be fixed with the next upcoming update from https://github.com/Myzel394/Alibi/pull/55

**Comment by Myzel394** [comment]
This is a MIUI device, isn't it?

**Comment by Notunderscore** [comment]
Okay, thanks, I'll see.


By the way, 
> This is a MIUI device, isn't it?
It's an OPPO, sorry I didn't mention it 😉
