### ISSUE TITLE
F-Droid listing

### ISSUE THREAD

**Issue by IzzySoft** [Myzel394/Alibi#61]
First congrats to your listing at F-Droid! At this point apps are usually removed from my repo – but your Readme still links to it. Will you replace that badge & link by F-Droid's?

**Comment by Myzel394** [comment]
Thanks for the hint! Added the new link

**Comment by IzzySoft** [comment]
Thanks! As your app was just added to F-Droid 3 days ago, I'll leave it up for another week and then remove it here (as customary: 10..14 days overlap). Should you one day need it back for some reason, just ring my bell.
