### ISSUE TITLE
Add video support

### ISSUE THREAD

**Issue by pabloscloud** [Myzel394/Alibi#7]
Just leaving this here as feedback 😅

**Comment by Myzel394** [comment]
I'll definitely add that! I'm currently adding this, but it seems as if background video recording is quite complex. So video recording **will come**, but it will take some time :/

**Comment by pabloscloud** [comment]
All good 😁 love the design already!

**Comment by aha999** [comment]
That's great! Having a background video recording would make it the best opensource dashcam app!

**Comment by ovizii** [comment]
The current description is:

> Use your phone as a dashcam and save the last 30 minutes when you need it.

How can it act as a dashcam without video recording? Cam is short for camera and not for audiorecorder 😅

**Comment by Myzel394** [comment]
@ovizii I'm working on adding video support. Unfortunately, this seems to be much harder than expected and I'm quite busy personally, so it'll take some time for me to implement it :/

**Comment by ovizii** [comment]
I understand, I was just joking about the "dashcam feature" as I was looking left and right to find the video feature :-) 
You'll get to it when you get to it I guess.

**Comment by Myzel394** [comment]
@Simplenuity thank you very much, this is very kind of you. I was able to read the code, unfortunately, it uses a very old API which shouldn't be used according to the docs :/ However, I might fallback to it as Google offers like no usable docs for their new APIs :(

**Comment by ovizii** [comment]
> No metadata in the output file. So when one has to share a video with strangers no data are provided about the device or geoposition where it has been recorded. Security reason (think politicians or journalist in dangerous countries). This concern the audio recording too.

I'm not so sure about that, I mean that is the whole point of this app and its in the name “alibi”.

**Comment by ovizii** [comment]
> > I'm not so sure about that, I mean that is the whole point of this app and its in the name “alibi”.
> 
> There are cases where your presence must be concealed. Alibi’s role is to document real facts through multimedia evidence.
> 
> Alibi does not necessarily have to add more information.
> 
> Close your house they deal drugs. You just need to send a video to the nearest police station. Also anonymously. There are hundreds of similar situations, in which the sender must remain anonymous in order not to risk their own safety.

I understand your point. I was simply seeing it from a different perspective: seeing that an alibi is defined as "a claim or piece of evidence that one was elsewhere when an act, especially a criminal one, is alleged to have taken place." I thought that without the involved metadata (or having it cleaned out of the file) it wouldn't count as evidence. 

Just my 2c, I do not refute the points you are making as the use case you describe is obviously also legit. I guess it's up to the author of the app to decide. :-)

**Comment by Myzel394** [comment]
> I thought that without the involved metadata (or having it cleaned out of the file) it wouldn't count as evidence.

I'm not a lawyer but I'd be surprised if it wouldn't. So my assumption is: If the app processes the file in a deterministic way, it shouldn't be a reason to exclude it as evidence. There are also other apps like the builtin Google Camera app that also postprocess an image (for example to use AI to enhance the image), and I've never heard that this is a reason for it being no evidence.

I won't add extra metadata intentionally because of the reason @serrq said. It would do more harm if we expose someone "accidentally" via metadata than it is to not have enough information available to condemn someone. I also think that the latter scenario is very very unlikely as a person would probably be able to remember at least roughly where they recorded something.

Aaaand lastly, of course I also hope that Alibi never needs to be presented in court and there are no more crimes in the world :)

**Comment by Myzel394** [comment]
Aaaaaall right guys, finally, after a way too long wait I'm very close to add video support to Alibi! [You can already try out a debug build here](https://github.com/Myzel394/Alibi/suites/19052307472/artifacts/1115191177)! (Download the zip, extract it and install `app-universal-debug.apk`) There are still some bugs here and there, which I want to fix before publishing the update. However, I'm sure I'll be able to resolve them within this year! :)
I'd be very happy if you already try out the debug build and tell me what you like / what you don't like / what bugs you encounter / what's missing etc.

And thanks for all your patience, I'm very happy to finally find a solution to this!

**Comment by Jammmmm** [comment]
Just today I thought my phone isn't really doing anything when I drive so it can be used as a dashcam. The only other recent(ish) app I came across was https://github.com/maxneaga/open_dash_cam_android but it has no builds available for download. A quick search later and I came across Alibi and this debug build :)

I gave it a quick try walking around the house and it seems to work really well. Videos are recording and saving. I was able to change the quality and bitrate and confirmed they work by looking at file size.

The only thing I would suggest is maybe a button to turn on/off video display as it's recording so you know you have the camera positioned properly.

But other than that, no complaints here. Thanks for your work, @Myzel394!

**Comment by Jammmmm** [comment]
> you can temporarily look at the preview before beginning the recording by holding down on the "Start Recording" button.

I just gave it a try and yes, that's good enough for me. Thanks again! :D

**Comment by Jammmmm** [comment]
> * when recording **video** and then I select "Save Recording" I get a notification for a split second and then I'm back to the start screen of the app. No dialog (as mentioned in the notification) to actually save the file

I came across this too when I was testing. I use Android 9 on an LG device.

I started recording video, then minimized it and used another app that played video (so I could see how audio was being captured). I then stopped the video went back to the app, paused the recording and tried to save. I didn't get a dialog. Not even a toast/notification.

With that said, I haven't been able to reproduce it which is why I didn't report it as a bug. But I guess it is if we both experienced it.

**Comment by Myzel394** [comment]
@Jammmmm and @Simplenuity does this only happen on old devicees or did also face this on new devices?

**Comment by Jammmmm** [comment]
> @Jammmmm and @Simplenuity does this only happen on old devicees or did you also face this on new devices?

Unfortunately I only have access to an old device so I couldn't say.

**Comment by Myzel394** [comment]
@Jammmmm and @Simplenuity are you running a custom rom of Android such as LineageOS, GrapheneOS etc?

**Comment by Jammmmm** [comment]
> @Jammmmm and @Simplenuity are you running a custom rom of Android such as LineageOS, GrapheneOS etc?

Nothing custom on my end. Stock Android, but my device is rooted with Magisk. That might be the only thing that could interfere but it's doubtful.

**Comment by Myzel394** [comment]
Unfortunately, after installing LineageOS 20 on a phone myself, I was still not able to reproduce the issue :( @Simplenuity and @Jammmmm I know it's a long discussion already, but could you record a screen recording of the issue you're facing and upload it here? If you don't feel comfortable sharing the recording here on GitHub, [you can also contact me in another way](https://github.com/Myzel394/contact-me?tab=readme-ov-file#contact-information).

**Comment by Jammmmm** [comment]
@Myzel394 I'm unable to reproduce the problem so I wouldn't be able to give a screen recording. Hopefully @Simplenuity can help in that regard.

**Comment by Myzel394** [comment]
@Jammmmm and @Simplenuity can you try [installing the newest debug build](https://github.com/Myzel394/Alibi/actions/runs/7373106814/artifacts/1141314979) and seeing if the error still persists? You can also try changing the batches folder location in the advanced settings section if it's still not working

**Comment by pabloscloud** [comment]
I'm confused. Has video support been added and people are just complaining here cause then I'll close this issue and a new issue should be created as bug. Cause this is a feature-request and not a bug.

**Comment by Myzel394** [comment]
@pabloscloud Video support is almost available; I opened a PR and created a dev build for people to try out. Unfortunately, some people reported some issues on lower Android versions. I'm currently fixing those last bugs, but then there will be a huge update with video support and other new features as well! :)

**Comment by pabloscloud** [comment]
how do people have a problem with it if it's not available haha. Well, great it's being worked on :)

**Comment by Myzel394** [comment]
@pabloscloud I created a development version which you can already try out (see https://github.com/Myzel394/Alibi/actions/runs/7378563060/artifacts/1141958786)

**Comment by pabloscloud** [comment]
ahhhhhhh, now everything makes sense lol

**Comment by pabloscloud** [comment]
Yes :)
