### ISSUE TITLE
video recording: control buttons missing in landscape orientation

### ISSUE THREAD

**Issue by Simplenuity** [Myzel394/Alibi#71]
Hi @Myzel394,

Video support has made your app a great dashcam option. Many thanks!

First test runs have been successful. I only came across a minor glitch so far:
In landscape orientation the control buttons for `delete`, `pause`, and `save` are missing.

workaround: turn to portrait orientation to access them

**Comment by Myzel394** [comment]
Thanks for the hint, this will be fixed with the next release! :)
