### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by travalanche08** [Myzel394/Alibi#72]
I could use some instructions for this. I don't know what I'm doing wrong, but I can't figure out how to turn it off (aside from pausing) or where the file is actually saved to when using the Private, encrypted storage" option.

**Comment by Myzel394** [comment]
Agreed, I will add an explanation. Here's the explanation:

To protect your privacy, Alibi stores its batches into its own private, encrypted storage. This storage is only accessible by Alibi and can\t be accessed by other apps or by a possible intruder. Once you save the recording, you will be asked where you want to save the recording to.

So if you choose the private, encrypted storage option, **you are not able to manually view or download the individual batches**. If you want to do that, you can use the DCIM option or specify a custom folder.

**Comment by Myzel394** [comment]
And regarding your other question:

> I don't know what I'm doing wrong, but I can't figure out how to turn it off (aside from pausing) 

You can pause, delete / abort the recording and save it.
