### ISSUE TITLE
Include graphical overlays into the UI (current speed, GPS / GPX, facing direction, )

### ISSUE THREAD

**Issue by natrius** [Myzel394/Alibi#78]
I think it would be neat that putting a GPX/GPS-Traces for the recorded video in the corner. With a OpenStreetMap-background, like a minimap in some computer games. 

There could be more stuff included like

- current speed in KM/H (or miles?) 
- direction-compass on the top of the video

All separately included or excluded and maybe even movable. If wanted/needed i can open separate issues for everything. 

I guess there are quite some people with bike who would like to use the app when riding as well. I guess some would be using this in a car as well.

**Comment by Myzel394** [comment]
Sorry, but this is out of scope for Alibi. 

However, you could check out my other app [locus](https://github.com/Myzel394/locus) which offers location sharing / gps tracking :D

**Comment by natrius** [comment]
Thanks for the hint, but i really thought about when sharing a video it would be nice to have stuff like that included immediately. Thanks for your app! :)

**Comment by Myzel394** [comment]
> Thanks for the hint, but i really thought about when sharing a video it would be nice to have stuff like that included immediately.

I agree that this is a cool feature request. However, I don't want to add too much "fluff" that can be outsourced into other apps specialized for those features. Especially since I'm mainly working on Alibi all by myself, it's much harder to maintain features :/
