### ISSUE TITLE
Scheduled surveillance and auto save mode

### ISSUE THREAD

**Issue by serrq** [Myzel394/Alibi#8]
I still had no idea how to make the most of this app.

Then I realized that at night it's totally useless, so I can rule out using it at night.

There are times during the day when I need "coverage" and other times when I am alone and do not need any.
Limiting the use of Alibi is also useful to save battery and preserve the health of the flash drive.

In scheduling mode I thought that the batches would save themselves, and that at a later time I would discard them as irrelevant.

I think that's a better approach than hitting save. Maybe I forget or I'm in an interview and I can't handle the phone.
It is extremely important that I can decide afterwards what is good and what is not.

**Comment by Myzel394** [comment]
For this case I think it might be better to use an app like [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate) as it gives you much more control and is specialized on doing such tasks. However, Alibi currently won't work with it, but it may be a good idea adding support for it later.

**Comment by Myzel394** [comment]
I'm sorry but this is out of scope for Alibi :/. There might be other FLOSS alternatives to Automate. If you need to record audio always at a given time and later want to decide what you want to keep and what not, a regular audio recorder fits better here.
