### ISSUE TITLE
Refactor code to follow android architecture guidelines

### ISSUE THREAD

**Issue by materoy** [Myzel394/Alibi#82]
This is a great app with a potential. I see the current code follows flutter/dart architecture, while it works well, it could be improved architecturally to make it easy to work with for current and future contributors. 
There's a couple of official android samples by google eg: [architecture samples](https://github.com/android/architecture-samples) and [now in android app](https://github.com/android/nowinandroid). That I use as a guide. 
This is something I'm willing to do myself, just give me the go ahead and if this is something ya'll want as well.
No rush though, it's a long term change.

**Comment by Myzel394** [comment]
I'm honestly not a big fan of architectures such as clean code for apps. I have only worked with small apps such as Alibi or locus, so nothing business-related yet, and in those cases I do prefer this loose / manual style. I may change my opinion once I worked with larger codebases, but for the moment, I think it's easier to work with this setup.
