### ISSUE TITLE
[Feature Request] Continue recording after saving?

### ISSUE THREAD

**Issue by dzx-dzx** [Myzel394/Alibi#83]
Sorry if the issue has been discussed before.
Currently once the recording is saved, the process is stopped and must be initiated again manually. What about letting it continue without cease?

**Comment by Myzel394** [comment]
What's the problem with manually starting another recording? :O

**Comment by dzx-dzx** [comment]
Just…an alternative way of using it? I want to continue the recording indefinitely.

**Comment by xandro0777** [comment]
Would be expected behavior for me. After reading through https://github.com/Myzel394/Alibi/issues/76 I was actually thinking this were default behavior. As mentioned in that issue some settings and wording are not yet completely intuitive.

**Comment by Myzel394** [comment]
I'm sorry but Alibi in it's form is not expected to record and permanently save recordings indefinitely. It's more meant as a dashcam.

However, I could offer to implement an auto-save functionality. So you can trigger an auto-save at anytime in the app and also set up automatic auto-saves to happen in the background. What do you think about this @dzx-dzx ?

**Comment by dzx-dzx** [comment]
I…might need to clarity myself. I don't want recordings of indefinite length. What I want is, while the app is running indefinitely (and keep the last, say, two hours of recording), I can save the recording from time to time instead of ending it on the first time.

If that's truly impossible, what about automatically starting a new recording once the last one is saved, or at least prompt to ask so?

**Comment by dzx-dzx** [comment]
Sorry if this ping appears rude... @Myzel394 
Also the auto-save feature you proposed... could be useful for others, but I can't think of a routine scenario that generates such need.

**Comment by Myzel394** [comment]
Fixed in https://github.com/Myzel394/Alibi/pull/94 - you can hold down on the save button to save the current state and Alibi will continue recording. This will be available with the next upcoming update.
