### ISSUE TITLE
Wrong/Confusing information 

### ISSUE THREAD

**Issue by xandro0777** [Myzel394/Alibi#85]

**Comment by xandro0777** [comment]
The end time of the recording is rather often totally wrong.

I would suggest to change the wording to something like the last 3 hours are in storage and can be exported or audio information since XXX is in storage and can be exported.

![Screenshot_2024-03-05-14-15-01-93_206bcd8985d1af7b1eeb269fda67f42e](https://github.com/Myzel394/Alibi/assets/43711649/653f644a-e15d-434a-bd3a-bff2e885aac0)
![Screenshot_2024-03-05-14-14-55-54_206bcd8985d1af7b1eeb269fda67f42e](https://github.com/Myzel394/Alibi/assets/43711649/7ce66fd6-567d-4fa6-93f5-2342c6d47462)

**Comment by Myzel394** [comment]
I'm a bit confused. What text are you exactly talking about? Are you talking about the "Saving now ..." or the "Recording started at 13:41"?

**Comment by xandro0777** [comment]
Saving now. Also compare with the time in the notification line.

**Comment by Myzel394** [comment]
That text always shows your time - the max duration. So in your example it shows 14:14 - 3 hours. Because you have only recorded for ~33 minutes yet, it will show your time - 33 minutes.

**Comment by xandro0777** [comment]
Recording started at 13:41 is correct.

**Comment by xandro0777** [comment]
Look again. At 14:14 it says saving now will save until 13:41.. this can not be right.

**Comment by Myzel394** [comment]
> Well it says will save until XXX and that time is plain wrong

I still don't get why this is wrong. What time do you expect to be there? 14:14 - 33 minutes is 13:41

**Comment by xandro0777** [comment]
If I hit save at 14:14 I expect it will save until 14:14.

**Comment by xandro0777** [comment]
Yes, that would be much better imho. I would also consider the wording "export" instead of "save" because technically that is more fitting and the word export is also used in the settings.

Also in a few other places the wording could use an improvement to reduce confusion of new users and I will look at that in a separate issue.
